// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1bE-_VpZigPtu2kYw9ol0dnLh3gZzQoI',
    appId: '1:728410557347:web:60f966556bcc7005ece816',
    messagingSenderId: '728410557347',
    projectId: 'rifuniv',
    authDomain: 'rifuniv.firebaseapp.com',
    storageBucket: 'rifuniv.firebasestorage.app',
    measurementId: 'G-K3Q4EPG3QN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwzj65CNrSPLeoShOtNdcUviwaBIEcgPY',
    appId: '1:728410557347:android:d61681beb73b1cd4ece816',
    messagingSenderId: '728410557347',
    projectId: 'rifuniv',
    storageBucket: 'rifuniv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Cf0eeHcTR2TxJIgx90bxhJ9opUQg6_c',
    appId: '1:728410557347:ios:70c86755489f43f7ece816',
    messagingSenderId: '728410557347',
    projectId: 'rifuniv',
    storageBucket: 'rifuniv.firebasestorage.app',
    androidClientId: '728410557347-6dmarrg2u0a9n8h39c2sle5fjcab28hh.apps.googleusercontent.com',
    iosClientId: '728410557347-utvpk3au9sotoceor1otd6aueheii8kf.apps.googleusercontent.com',
    iosBundleId: 'com.example.rifrif',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5Cf0eeHcTR2TxJIgx90bxhJ9opUQg6_c',
    appId: '1:728410557347:ios:70c86755489f43f7ece816',
    messagingSenderId: '728410557347',
    projectId: 'rifuniv',
    storageBucket: 'rifuniv.firebasestorage.app',
    androidClientId: '728410557347-6dmarrg2u0a9n8h39c2sle5fjcab28hh.apps.googleusercontent.com',
    iosClientId: '728410557347-utvpk3au9sotoceor1otd6aueheii8kf.apps.googleusercontent.com',
    iosBundleId: 'com.example.rifrif',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1bE-_VpZigPtu2kYw9ol0dnLh3gZzQoI',
    appId: '1:728410557347:web:236074d37a225069ece816',
    messagingSenderId: '728410557347',
    projectId: 'rifuniv',
    authDomain: 'rifuniv.firebaseapp.com',
    storageBucket: 'rifuniv.firebasestorage.app',
    measurementId: 'G-F21C42752Z',
  );
}
